export const theme = {
  colors: {
    blueColor: '#20dce4',
    pinkColor: '#b03cac',
    pinkSubColor: '#e854dc',
    whiteColor: '#ffffff',
    blackColor: '#282424',
    darkRedColor: '#201c1c',
  },
  fonts: {
    xxxsmall: '0.75rem',
    xxsmall: '0.9rem',
    xsmall: '1.125rem',
    small: '1.5rem',
    medium: '2.25rem',
    large: '3rem',
    xlarge: '3.75rem',
    xxlarge: '4.5rem',
    huge: '5.25rem',
    xhuge: '6rem',
  },
  breakpoints: {
    small: '(max-width: 600px)',
    medium: '(max-width: 900px)',
    large: '(max-width: 1200px)',
  },
  spacings: {
    tiny: '0.5rem',
    xxxsmall: '0.75rem',
    xxsmall: '1rem',
    xsmall: '1.25rem',
    small: '1.5rem',
    medium: '2.25rem',
    large: '3rem',
    xlarge: '3.75rem',
    xxlarge: '4.5rem',
    huge: '5.25rem',
    xhuge: '6rem',
  },
}